### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by leseigneur** [tinkerspy/Automaton-Machine-Editor#2]
Hello tinkerspy,
I'm trying to run your Machine editor on my Ubuntu (16) dev server with PHP 5.6 & nginx
It somewhats works, only .h and .cpp generated files complain about simplexml :

```
Fatal error: Call to undefined function simplexml_load_string() in /var/www/html/lib/libatm.php on line 510
/* 
Automaton::ATML::begin - Automaton Markup Language

<?xml version="1.0" encoding="UTF-8"?>
<machines>
  <machine name="Atm_machine">
    <states>
    </states>
    <events>
    </events>
    <connectors>
    </connectors>
    <methods>
    </methods>
  </machine>
</machines>

Automaton::ATML::end 
*/
```
At first, I did not have simplexml installed, and that yield to blank pages and error messages in nginx error.log. I have fixed that now and no more have errors in the log file.

Here is the error file, seams clean to me:

```
jy@dev-ubuntu:/var/www/html$ tail -f /var/log/nginx/error.log
2016/11/11 14:24:07 [error] 1345#1345: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 522
PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 531
PHP message: PHP Notice:  Use of undefined constant events - assumed 'events' in /var/www/html/lib/libatm.php on line 551
PHP message: PHP Notice:  Use of undefined constant events - assumed 'events' in /var/www/html/lib/libatm.php on line 560
PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 564
PHP message: PHP Notice:  Use of undefined constant connectors - assumed 'connectors' in /var/www/html/lib/libatm.php on line 569
PHP message: PHP Notice:  Undefined index: create in /var/www/html/index.php on line 52
PHP message: PHP Notice:  Undefined index: txt_rename in /var/www/html/index.php on line 61" while reading response header from upstream, client: 192.168.1.101, server: 192.168.1.30, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "192.168.1.30", referrer: "http://192.168.1.30/cppheader.php"
2016/11/11 14:24:10 [error] 1345#1345: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 522
PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 531
PHP message: PHP Notice:  Use of undefined constant events - assumed 'events' in /var/www/html/lib/libatm.php on line 551
PHP message: PHP Notice:  Use of undefined constant events - assumed 'events' in /var/www/html/lib/libatm.php on line 560
PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 564
PHP message: PHP Notice:  Use of undefined constant connectors - assumed 'connectors' in /var/www/html/lib/libatm.php on line 569
PHP message: PHP Notice:  Undefined index: txt_rename in /var/www/html/index.php on line 61" while reading response header from upstream, client: 192.168.1.101, server: 192.168.1.30, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "192.168.1.30", referrer: "http://192.168.1.30/index.php"
2016/11/11 14:24:13 [error] 1345#1345: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: coll in /var/www/html/navigation.php on line 11
PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 522
PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 531
PHP message: PHP Notice:  Use of undefined constant events - assumed 'events' in /var/www/html/lib/libatm.php on line 551
PHP message: PHP Notice:  Use of undefined constant events - assumed 'events' in /var/www/html/lib/libatm.php on line 560
PHP message: PHP Notice:  Use of undefined constant states - assumed 'states' in /var/www/html/lib/libatm.php on line 564
PHP message: PHP Notice:  Use of undefined constant connectors - assumed 'connectors' in /var/www/html/lib/libatm.php on line 569" while reading response header from upstream, client: 192.168.1.101, server: 192.168.1.30, request: "GET /cppcode.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "192.168.1.30", referrer: "http://192.168.1.30/index.php"
```

I have spent several hours on that, but I'm stuck now.
Your help would be much appreciated.
jy :)

**Comment by tinkerspy** [comment]
Hi jy,

I don't think I ever did a test install on a fresh system, my bad...

I installed a fresh copy of Centos 7, fixed some of the PHP warnings and (fortunately) I ran into the same problem you did. The problem is that even if you marked the machines directory as writable, SElinux will stop Apache from writing to it. To make that possible the easiest way is to disable SElinux. I pretty much disable that standard on my machines so I never ran into it.

So download the last commit, set SELINUX=disabled, reboot and give it another try.

Rgdz,
Tinkerspy

**Comment by leseigneur** [comment]
Hi Tinkerspy,
I have checked SELINUX state, it is already disabled.
I have updated the code per your recommendation but I have the same issue.
I don't believe it is an access issue to the machines directory, since there are files and directories created by your code there. Only, the content of Template.h & work/Machine.h says : "Fatal error: Call to undefined function simplexml_load_string() in /var/www/html/lib/libatm.php on line 510".
:/

**Comment by tinkerspy** [comment]
You must give the Apache user write access to the 'machines' directory. 

You must also install the php7.0-xml package.

https://wpml.org/errata/php-7-possible-issues-simplexml/

Rgdz,
Tinkerspy

**Comment by leseigneur** [comment]
Hi tinkerspy
I have upgraded my php to 7.0 just now. Installed xmlrpc and enabled it in both /etc/php/7.0/cli/php.ini and /etc/php/7.0/fpm/php.ini 
Still the same issue

I use nginx instead of Apache. 
It has write access to 'machines' directory : 

```
jy@dev-ubuntu:/var/www/html/machines/vftko9selskn3akopfjv9pnse0$ ll
total 28
drwxr-xr-x 3 www-data www-data 4096 Nov 15 11:53 ./
drwxrwxrwx 3 www-data www-data 4096 Nov 15 11:53 ../
-rw-r--r-- 1 www-data www-data  224 Nov 15 11:53 new.atml
-rw-r--r-- 1 www-data www-data  456 Nov 15 11:53 Template.cpp
-rw-r--r-- 1 www-data www-data  458 Nov 15 11:53 Template.h
-rw-r--r-- 1 www-data www-data  458 Nov 15 11:53 Template.ino
drwxr-xr-x 2 www-data www-data 4096 Nov 15 11:53 work/
```

The issue : 

```
> jy@dev-ubuntu:/var/www/html/machines/vftko9selskn3akopfjv9pnse0$ cat Template.cpp
> 
> Fatal error: Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/lib/libatm.php:510
> Stack trace:
> #0 /var/www/html/lib/libatm.php(115): ATM_Machine->from_xml('<?xml version="...', 0)
> #1 /var/www/html/lib/libatm.php(41): ATM_Collection->from_xml('<?xml version="...')
> #2 /var/www/html/templates/code-001.php(6): ATM_Collection->__construct('<?xml version="...')
> #3 {main}
>   thrown in /var/www/html/lib/libatm.php on line 510
```

There must be something obvious I don't see.
What I don't understand is that I can run this code successfully : 

```
<?php

if (function_exists('simplexml_load_string')) {
    echo "simpleXML functions load string available.<br />\n";
} else {
    echo "simpleXML functions are not available.<br />\n";
}
```

**Comment by tinkerspy** [comment]
Have you tried this? 
sudo apt-get install php7.0-xml

Rgdz,
Tinkerspy

**Comment by leseigneur** [comment]
Yes, it is already installed.

**Comment by tinkerspy** [comment]
I'm sorry, then I'm out of ideas...

Is SimpleXML in the 'php -m' listing?

Rgdz,
Tinkerspy
